version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Superpower.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: kkMZ/vegQUkZw6TKvA+zdG3o9sI7bY7IwtDQzxD37wFyoMC+qg5rIsuUyHbq1Qcb
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Superpower.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
